Add date to create-links backup file name

diff --git a/create-links b/create-links
--- a/create-links
+++ b/create-links
@@ -12,8 +12,9 @@ for file in [a-zA-Z]* ; do
             echo "  Removing symbolic link ~/.$file"
             rm ~/."$file"
         elif [[ -a ~/."$file" ]] ; then
-            echo "  ~/.$file exists. Moving it to ~/.$file.back"
-            mv ~/."$file" ~/."$file".back || echo "Couldn't move ~/.$file to ~/.$file.back!"
+            date=$(date '+%FT%T');
+            echo "  ~/.$file exists. Moving it to ~/.$file.back.$date"
+            mv ~/."$file" ~/."$file".back.$date || echo "Couldn't move ~/.$file to ~/.$file.back.$date!"
         fi
 
         ln -s `pwd`/"$file" ~/."$file" && echo "Linked ~/.$file to `pwd`/$file" || echo "Couldn't link ~/.$file to `pwd`/$file!"
